apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cardsdb
spec:
  serviceName: cardsdb
  replicas: 1
  selector:
    matchLabels:
      app: cardsdb
  template:
    metadata:
      labels:
        app: cardsdb
    spec:
      containers:
        - name: cardsdb
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: knightind-configmap
                  key: CARDS_MYSQL_DATABASE
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: knightind-configmap
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: cardsdb
spec:
  type: ClusterIP
  selector:
    app: cardsdb
  ports:
    - protocol: TCP
      port: 3308
      targetPort: 3306
